### ISSUE TITLE
File yo dial target host

### ISSUE THREAD

**Issue by chandrakanth877-zz** [wongnai/docker-grpcui#2]
When i use docker run -eGRPCUI_SERVER=127.0.0.1:443 -p8080:8080 wongnai/grpcui

**Failed to dial target host "127.0.0.1:443": dial tcp 127.0.0.1:443: connect: connection refused**

Am getting the above exception. Please let me know is there any way to resolve this issue

**Comment by lechu445** [comment]
@chandrakanth877 this is due to how docker works.
You are trying to bind the service to it's localhost. Instead, use docker host localhost:
```bash
docker run -eGRPCUI_SERVER=host.docker.internal:443 -p8080:8080 wongnai/grpcui
```
or (but only on Windows):
```bash
docker run -eGRPCUI_SERVER=docker.for.win.localhost:443 -p8080:8080 wongnai/grpcui
```
